# Generated by Django 5.0.14 on 2026-04-04 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohub_app', '0004_debtsettlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма долга')),
                ('amount_returned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сколько уже вернули')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок возврата')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('partially_paid', 'Частично погашен'), ('paid', 'Полностью погашен'), ('overdue', 'Просрочен')], default='active', max_length=20, verbose_name='Статус')),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание')),
                ('reminder_count', models.PositiveIntegerField(default=0, verbose_name='Сколько раз напоминали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_taken', to=settings.AUTH_USER_MODEL, verbose_name='Кто взял деньги')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_given', to=settings.AUTH_USER_MODEL, verbose_name='Кто дал деньги')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='cohub_app.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Ручной долг',
                'verbose_name_plural': 'Ручные долги',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма возврата')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cohub_app.loan', verbose_name='Долг')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Кто вернул')),
            ],
            options={
                'verbose_name': 'Платеж по долгу',
                'verbose_name_plural': 'Платежи по долгам',
                'ordering': ['-paid_at'],
            },
        ),
    ]
