# Generated by Django 5.0.14 on 2026-04-10 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohub_app', '0005_loan_loanpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReassignmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('illness', 'Заболел(а)'), ('family', 'Семейные обстоятельства'), ('exam', 'Экзамен / учеба'), ('work', 'Срочная работа'), ('trip', 'Отъезд / дорога'), ('other', 'Другая причина')], default='other', max_length=20, verbose_name='Причина')),
                ('custom_message', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принят'), ('declined', 'Отклонён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('response_note', models.CharField(blank=True, max_length=255, verbose_name='Ответ на запрос')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда ответили')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reassignment_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Кто просит')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reassignment_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Кому отправлено')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reassignment_requests', to='cohub_app.room', verbose_name='Комната')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_requests', to='cohub_app.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Запрос на передачу задачи',
                'verbose_name_plural': 'Запросы на передачу задач',
                'ordering': ['-created_at'],
            },
        ),
    ]
