# Generated by Django 5.0.14 on 2026-04-24 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohub_app', '0008_expense_is_shared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Пробный период'), ('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], default='trial', max_length=20, verbose_name='Статус подписки')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало пробного периода')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец пробного периода')),
                ('paid_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало оплаченного периода')),
                ('paid_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец оплаченного периода')),
                ('amount', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Сумма подписки (₸)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
