# Generated by Django 5.0.14 on 2026-06-01 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohub_app', '0009_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-created_at'], name='chat_room_created_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['room', '-date'], name='expense_room_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['room', 'status'], name='task_room_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='task_assignee_status_idx'),
        ),
    ]
