# Generated by Django 5.0.14 on 2026-06-01 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohub_app', '0010_chatmessage_chat_room_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100, verbose_name='Имя задачи')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Выполнена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Сделано попыток')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Максимум попыток')),
                ('result', models.TextField(blank=True, verbose_name='Результат или текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Фоновая задача',
                'verbose_name_plural': 'Фоновые задачи (очередь)',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='bgtask_status_created_idx')],
            },
        ),
    ]
