# Generated by Django 5.0.14 on 2026-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohub_app', '0011_backgroundtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', help_text='Глобальная роль пользователя: user или admin.', max_length=10, verbose_name='Роль (RBAC)'),
        ),
    ]
