# Generated by Django 5.0.14 on 2026-06-17 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohub_app', '0012_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('purpose', models.CharField(choices=[('subscription', 'PRO-подписка')], default='subscription', max_length=20, verbose_name='Назначение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('subscription_months', models.PositiveIntegerField(default=1, verbose_name='Месяцев подписки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Валюта')),
                ('provider', models.CharField(choices=[('bereke', 'Bereke Bank'), ('paypal', 'PayPal')], default='bereke', max_length=20, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён'), ('expired', 'Истёк'), ('refunded', 'Возврат')], default='created', max_length=20, verbose_name='Статус')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='Ключ идемпотентности')),
                ('provider_order_id', models.CharField(blank=True, max_length=128, verbose_name='ID заказа у провайдера')),
                ('provider_payment_id', models.CharField(blank=True, max_length=128, verbose_name='ID платежа у провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ (платёж)',
                'verbose_name_plural': 'Заказы (платежи)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=30, verbose_name='Тип события')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='В статус')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Сообщение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cohub_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Событие платежа',
                'verbose_name_plural': 'События платежей',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='order_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['provider', 'provider_order_id'], name='order_provider_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['order', 'created_at'], name='payevent_order_time_idx'),
        ),
    ]
